# Generated by Django 3.1 on 2022-01-12 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_operator', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Pengecekan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_pengecekan', models.CharField(choices=[('1', 'satu'), ('2', 'dua'), ('3', 'tiga')], default='pilih salah satu', max_length=1)),
            ],
        ),
    ]
