# Generated by Django 3.1 on 2022-01-12 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0002_operator_pengecekan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengecekan',
            name='shift_pengecekan',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='pilih salah satu', max_length=1),
        ),
    ]
