# Generated by Django 3.1 on 2022-01-12 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0003_auto_20220112_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengecekan',
            name='operator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='qc.operator'),
        ),
    ]
