# Generated by Django 3.1 on 2022-01-12 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0004_pengecekan_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengecekan',
            name='tgl_pengecekan',
            field=models.DateTimeField(default=None, verbose_name='Tanggal Pengecekan'),
        ),
    ]
