# Generated by Django 3.1 on 2022-01-12 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0005_pengecekan_tgl_pengecekan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengecekan',
            name='tgl_pengecekan',
            field=models.DateTimeField(default='', verbose_name='Tanggal Pengecekan'),
        ),
    ]
