# Generated by Django 3.1 on 2022-01-12 07:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0006_auto_20220112_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengecekan',
            name='tgl_pengecekan',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Tanggal Pengecekan'),
        ),
    ]
