# Generated by Django 3.1 on 2022-01-12 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0007_auto_20220112_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dtl_Pengecekan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pengecekan', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='qc.pengecekan')),
            ],
        ),
    ]
