# Generated by Django 3.1 on 2022-01-12 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0009_dtl_pengecekan_tbl_rongga_atas'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtl_pengecekan',
            name='id_group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='qc.masterdatamastergroup'),
        ),
    ]
