# Generated by Django 3.1 on 2022-01-12 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0010_dtl_pengecekan_id_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dtl_pengecekan',
            options={'verbose_name': 'A'},
        ),
    ]
