# Generated by Django 3.1 on 2022-01-12 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0011_auto_20220112_1617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dtl_pengecekan',
            options={'verbose_name': 'Detail Pengecekan'},
        ),
    ]
