# Generated by Django 3.1 on 2022-01-13 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0012_auto_20220112_1618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operator',
            options={'verbose_name': 'Operator'},
        ),
    ]
