# Generated by Django 3.1 on 2022-01-13 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0013_auto_20220113_0912'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dtl_pengecekan',
            options={'verbose_name': 'Detail Pengecekan', 'verbose_name_plural': 'Dtl_Pengecekan'},
        ),
    ]
