# Generated by Django 3.1 on 2022-01-13 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0014_auto_20220113_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tes', models.CharField(max_length=30)),
            ],
        ),
    ]
