# Generated by Django 3.1 on 2022-01-13 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0015_tes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tes',
        ),
    ]
