# Generated by Django 3.1 on 2022-01-17 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0018_dtl_pengecekan_id_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtl_pengecekan',
            name='kode_barang',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='qc.masterdatamasterbarang'),
        ),
    ]
