# Generated by Django 3.1 on 2022-01-17 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0019_dtl_pengecekan_kode_barang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dtl_pengecekan',
            name='id_group',
        ),
        migrations.RemoveField(
            model_name='dtl_pengecekan',
            name='id_kk',
        ),
        migrations.RemoveField(
            model_name='dtl_pengecekan',
            name='id_name',
        ),
        migrations.RemoveField(
            model_name='dtl_pengecekan',
            name='kode_barang',
        ),
        migrations.AddField(
            model_name='pengecekan',
            name='id_group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='qc.masterdatamastergroup'),
        ),
        migrations.AddField(
            model_name='pengecekan',
            name='id_kk',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='qc.formproduksikk'),
        ),
        migrations.AddField(
            model_name='pengecekan',
            name='id_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='qc.authgroup'),
        ),
        migrations.AddField(
            model_name='pengecekan',
            name='kode_barang',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='qc.masterdatamasterbarang'),
        ),
    ]
