# Generated by Django 3.1 on 2022-01-18 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0020_auto_20220117_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengecekan',
            name='customer',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
