# Generated by Django 3.1 on 2022-01-18 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0021_pengecekan_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterReject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_reject', models.CharField(default=None, max_length=50)),
                ('kategori', models.CharField(default=None, max_length=50)),
            ],
            options={
                'verbose_name': 'Jenis Reject',
            },
        ),
    ]
