# Generated by Django 3.1 on 2022-01-18 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0022_masterreject'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengecekan',
            name='mesin',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
