# Generated by Django 3.1 on 2022-01-18 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0023_pengecekan_mesin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengecekan',
            name='mesin',
            field=models.ForeignKey(default=None, max_length=30, on_delete=django.db.models.deletion.CASCADE, to='qc.masterdatamastermesin'),
        ),
    ]
