# Generated by Django 3.0.1 on 2022-01-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0025_masterreject_id_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterreject',
            name='kategori',
            field=models.CharField(choices=[('1', 'Fungsional'), ('2', 'Estetika'), ('3', 'Dimensi')], default='pilih salah satu', max_length=1),
        ),
    ]
