# Generated by Django 3.0.1 on 2022-01-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0026_auto_20220119_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterreject',
            name='kategori',
            field=models.CharField(choices=[('1', 'Fungsional'), ('2', 'Estetika'), ('3', 'Dimensi'), ('4', 'Atribut'), ('5', 'Critical'), ('6', 'Non Critical')], default='pilih salah satu', max_length=1),
        ),
    ]
