# Generated by Django 3.0.1 on 2022-01-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0027_auto_20220119_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterPilihan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_field', models.CharField(default=None, max_length=100)),
            ],
        ),
    ]
