# Generated by Django 3.0.1 on 2022-01-19 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0028_masterpilihan'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterDipilih',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ket', models.CharField(default=None, max_length=100)),
                ('field_dipilih', models.CharField(default=None, max_length=100)),
                ('id_group', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='qc.MasterdataMastergroup')),
                ('id_master_reject', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='qc.MasterReject')),
            ],
        ),
    ]
