# Generated by Django 3.0.1 on 2022-01-19 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0029_parameterdipilih'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterpilihan',
            name='id_dtl_pengecekan',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='qc.Dtl_Pengecekan'),
        ),
    ]
