# Generated by Django 3.0.1 on 2022-01-19 09:14

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0030_masterpilihan_id_dtl_pengecekan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterreject',
            name='kategori',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Fungsional'), ('2', 'Estetika'), ('3', 'Dimensi'), ('4', 'Atribut'), ('5', 'Critical'), ('6', 'Non Critical')], max_length=11),
        ),
    ]
