# Generated by Django 3.0.1 on 2022-01-20 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0032_auto_20220119_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterreject',
            name='aspekCritical',
            field=models.CharField(choices=[('Critical', 'Critical'), ('Non Critical', 'Non Critical')], default='pilih salah satu', max_length=50),
        ),
    ]
