# Generated by Django 3.0.1 on 2022-01-20 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0033_masterreject_aspekcritical'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtl_pengecekan',
            name='id_master_reject',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='qc.MasterReject'),
        ),
    ]
