# Generated by Django 3.0.1 on 2022-01-20 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0035_auto_20220120_0904'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dtl_Pengecekan',
            new_name='DetailPengecekan',
        ),
    ]
