# Generated by Django 3.0.1 on 2022-01-20 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0036_auto_20220120_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterpilihan',
            name='dimensi1',
            field=models.CharField(default=None, max_length=5),
        ),
        migrations.AddField(
            model_name='masterpilihan',
            name='dimensi10',
            field=models.CharField(default=None, max_length=5),
        ),
        migrations.AddField(
            model_name='masterpilihan',
            name='dimensi11',
            field=models.CharField(default=None, max_length=5),
        ),
        migrations.AddField(
            model_name='masterpilihan',
            name='dimensi12',
            field=models.CharField(default=None, max_length=5),
        ),
        migrations.AddField(
            model_name='masterpilihan',
            name='dimensi2',
            field=models.CharField(default=None, max_length=5),
        ),
        migrations.AddField(
            model_name='masterpilihan',
            name='dimensi3',
            field=models.CharField(default=None, max_length=5),
        ),
        migrations.AddField(
            model_name='masterpilihan',
            name='dimensi4',
            field=models.CharField(default=None, max_length=5),
        ),
        migrations.AddField(
            model_name='masterpilihan',
            name='dimensi5',
            field=models.CharField(default=None, max_length=5),
        ),
        migrations.AddField(
            model_name='masterpilihan',
            name='dimensi6',
            field=models.CharField(default=None, max_length=5),
        ),
        migrations.AddField(
            model_name='masterpilihan',
            name='dimensi7',
            field=models.CharField(default=None, max_length=5),
        ),
        migrations.AddField(
            model_name='masterpilihan',
            name='dimensi8',
            field=models.CharField(default=None, max_length=5),
        ),
        migrations.AddField(
            model_name='masterpilihan',
            name='dimensi9',
            field=models.CharField(default=None, max_length=5),
        ),
    ]
