# Generated by Django 3.0.1 on 2022-01-20 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0037_auto_20220120_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterpilihan',
            name='dimensi1',
        ),
        migrations.RemoveField(
            model_name='masterpilihan',
            name='dimensi10',
        ),
        migrations.RemoveField(
            model_name='masterpilihan',
            name='dimensi11',
        ),
        migrations.RemoveField(
            model_name='masterpilihan',
            name='dimensi12',
        ),
        migrations.RemoveField(
            model_name='masterpilihan',
            name='dimensi2',
        ),
        migrations.RemoveField(
            model_name='masterpilihan',
            name='dimensi3',
        ),
        migrations.RemoveField(
            model_name='masterpilihan',
            name='dimensi4',
        ),
        migrations.RemoveField(
            model_name='masterpilihan',
            name='dimensi5',
        ),
        migrations.RemoveField(
            model_name='masterpilihan',
            name='dimensi6',
        ),
        migrations.RemoveField(
            model_name='masterpilihan',
            name='dimensi7',
        ),
        migrations.RemoveField(
            model_name='masterpilihan',
            name='dimensi8',
        ),
        migrations.RemoveField(
            model_name='masterpilihan',
            name='dimensi9',
        ),
        migrations.RemoveField(
            model_name='parameterdipilih',
            name='ket',
        ),
        migrations.AddField(
            model_name='masterpilihan',
            name='ket',
            field=models.CharField(default=None, max_length=100, verbose_name='Keterangan'),
        ),
    ]
