# Generated by Django 3.0.1 on 2022-01-20 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0038_auto_20220120_0918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterpilihan',
            name='ket',
        ),
        migrations.AddField(
            model_name='parameterdipilih',
            name='ket',
            field=models.CharField(default=None, max_length=100, verbose_name='Keterangan'),
        ),
    ]
