# Generated by Django 3.0.1 on 2022-01-20 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0040_remove_masterpilihan_id_dtl_pengecekan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameterdipilih',
            name='field_dipilih',
        ),
        migrations.AddField(
            model_name='parameterdipilih',
            name='id_field_dipilih',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='qc.MasterPilihan', verbose_name='Parameter yang Dipilih'),
        ),
    ]
